---

- name: Include Redhat vars
  include_vars: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Stop selinux
  shell: setenforce 0
  args:
    executable: /bin/bash

- name: Template to edit selinux
  template:
    src=config.j2
    dest=/etc/selinux/config

- name: Install Php Group
  yum:  pkg={{ item }} state=present
  with_items:
     - httpd
     - php
     - php-common
     - php-mysqlnd
     - php-mbstring
     - php-gd
     - mod_ssl
  when: ansible_os_family == "RedHat"

- name: Template to edit httpd.conf
  template:
    src=httpd.j2
    dest=/etc/httpd/conf/httpd.conf

- name: Enable httpd
  systemd: enabled=yes name=httpd

- name: Start httpd
  systemd: state=started name=httpd

- firewalld:
    service: https
    permanent: true
    state: enabled

- firewalld:
    service: http
    permanent: true
    state: enabled

- name: Restart firewalld
  service:
    name: firewalld
    state: restarted

