---

- name: Include Redhat vars
  include_vars: redhat.yml
  when: ansible_os_family == "RedHat"
  
- name: Install Php Group
  yum:  pkg={{ item }} state=present
  with_items:
     - httpd
     - php
     - php-common
     - php-mbstring
     - php-gd
     - mod_ssl
  when: ansible_os_family == "RedHat"


